services:
  php:
    image: lotd/trongate-framework
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mxtransition-php
    volumes:
      - ./:/var/www/html
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
      - PHP_OPCACHE_MEMORY_CONSUMPTION=128
    networks:
      - mxtransition-network
    configs:
      - source: php-fpm-config
        target: /usr/local/etc/php-fpm.d/www.conf
    ports:
      - "8080:80"

  mariadb:
    image: mariadb:latest
    container_name: mxtransition-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: trongate
      MYSQL_USER: trongate
      MYSQL_PASSWORD: mxtransition_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - mxtransition-network

volumes:
  mariadb_data:

networks:
  mxtransition-network:

configs:
  php-fpm-config:
    file: ./docker/php-fpm.conf
